version: "3.8"

networks:
  elastic:

services:
  ### Nginx ################################################
  nginx:
    build:
      context: ./nginx
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    links:
      - "php:php"
      - "php-5.6:php-5.6"

  ### PHP ##################################################
  php-5.6:
    build:
      context: ./php/5.6
      args:
        - PHP_COMPOSER_URL=${PHP_COMPOSER_URL}
        - PHP_COMPOSER_REPO=${PHP_COMPOSER_REPO}
        - TZ=${TIMEZONE}
        - PHP56_REDIS_VERSION=${PHP56_REDIS_VERSION}
    ports:
      - "9001:9000"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

  php:
    build:
      context: ./php/latest
      args:
        - PHP_COMPOSER_URL=${PHP_COMPOSER_URL}
        - PHP_COMPOSER_REPO=${PHP_COMPOSER_REPO}
        - TZ=${TIMEZONE}
    ports:
      - "9000:9000"
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}

  ### MYSQL ################################################
  mysql:
    build:
      context: ./mysql
      args:
        - TZ=${TIMEZONE}
    command: --lower-case-table-names=2
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql

  ### Redis ################################################
  redis:
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ${DATA_PATH_HOST}/redis:/data

  ### MongoDB ##############################################
  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - ${DATA_PATH_HOST}/mongo:/data

  ### ElasticSearch ########################################
  elasticsearch:
    build:
      context: ./elasticsearch
      args:
        - ELK_VERSION=${ELK_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/elasticsearch:/usr/share/elasticsearch/data
    environment:
      - cluster.name=${ELASTIC_CLUSTER_NAME}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"      # ElasticSearch 是运行在 Java 上的，默认会开 2G 的内存空间，参数的作用就是限制内存使用的大小：512m
      - discovery.type=single-node            # 使用单节点
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    ports:
      - "9200:9200"
      - "9300:9300"

  ### Kibana ###############################################
  kibana:
    build:
      context: ./kibana
      args:
        - ELK_VERSION=${ELK_VERSION}
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
