services:
  mysql:
    # 最新的 LTS 版本是 9.7 （~2034年4月）
    # 另外的 LTS 版本是 8.4 （~2032年4月）
    image: mysql:9.7
    container_name: mysql
    restart: ${MYSQL_RESTART}
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${MYSQL_VOLUMES}:/var/lib/mysql
    networks:
      - environment_network

  postgres:
    # 这里只标注了 18 的版本，后续的子版本自动升级是可以接受的
    # 子版本的更新，仅用于修复Bug和解决安全问题
    # 如果无法接受这种，那就带上子版本号 18.x
    image: postgres:18
    container_name: postgres
    restart: ${POSTGRES_RESTART}
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ${POSTGRES_VOLUMES}:/var/lib/postgresql
    networks:
      - environment_network

volumes:
  mysql_data:
  postgres_data:

networks:
  environment_network:
